version: '3.8'

services:
  shadowsocksr:
    image: teddysun/shadowsocks-r:latest
    container_name: ssr
    restart: always
    ports:
      - "9000:9000"
      - "9000:9000/udp"
    volumes:
      - /etc/shadowsocks-r:/etc/shadowsocks-r
  workspace_backend:
    image: atticuszhou/work-space-fastapi-backend:latest
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    restart: always
  workspace_frontend:
    image: atticuszhou/work-space-vue-frontend:latest
    ports:
      - "80:80"
    environment:
      - VITE_FASTAPI_DOMAIN=${VITE_FASTAPI_DOMAIN}
    restart: always
