version: '3.8'

services:
  backend:
    image: atticuszhou/work-space-fastapi-backend:latest
    environment:
      PORT: 5000
    restart: always

  frontend:
    image: atticuszhou/work-space-vue-frontend:latest
    volumes:
      - vue_static_files:/app/dist
    environment:
      VITE_FASTAPI_DOMAIN: ${VITE_FASTAPI_DOMAIN}

    restart: always

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - vue_static_files:/usr/share/caddy:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      DOMAIN: ${DOMAIN}
      BACKEND_SERVICE: backend:5000
    depends_on:
      - backend
      - frontend

volumes:
  caddy_data:
  caddy_config:
  vue_static_files:
